name: Build and deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:ontap-bot-${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Set up nomad cli
        run: |
          curl https://releases.hashicorp.com/nomad/1.7.2/nomad_1.7.2_linux_amd64.zip -o nomad.zip
          unzip nomad.zip
          chmod +x nomad
          sudo mv nomad /bin/nomad

      - name: Setup cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/download/2023.10.0/cloudflared-linux-amd64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb

      - name: Spawn cloudflared tunnel
        env:
          TUNNEL_SERVICE_TOKEN_ID: ${{ secrets.TUNNEL_SERVICE_TOKEN_ID }}
          TUNNEL_SERVICE_TOKEN_SECRET: ${{ secrets.TUNNEL_SERVICE_TOKEN_SECRET }}
        run: sudo nohup cloudflared access tcp --hostname nomad-tcp.justdockerize.it --url localhost:4646 &

      - name: Deploy to nomad
        env:
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
        run: |
          nomad job run \
            -var docker_user=${{ secrets.DOCKERHUB_USERNAME }} \
            -var docker_password=${{ secrets.DOCKERHUB_TOKEN }} \
            -var dockerhub_repository=${{ vars.DOCKERHUB_REPOSITORY }} \
            -var image_tag=ontap-bot-${{ github.sha }} \
            -var ontap_api_key=${{ secrets.ONTAP_API_KEY }} \
            -var telegram_bot_token=${{ secrets.TELEGRAM_BOT_TOKEN }} \
            -var openai_api_key=${{ secrets.OPENAI_API_KEY }} \
            ./ci/ontap-bot.nomad
